/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.assignment;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;

/**
 *
 * @author rong0
 */
public class AdminDisplayPage extends javax.swing.JFrame {

    /**
     * Creates new form CoachDisplayPage
     */
    public AdminDisplayPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coachIdButton = new javax.swing.JButton();
        ratingButton = new javax.swing.JButton();
        sportIdButton = new javax.swing.JButton();
        studentIdButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        coachIdButton.setText("Search By Coach Id");
        coachIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachIdButtonActionPerformed(evt);
            }
        });

        ratingButton.setText("Search By Rating");
        ratingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingButtonActionPerformed(evt);
            }
        });

        sportIdButton.setText("Search By Sport Id");
        sportIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportIdButtonActionPerformed(evt);
            }
        });

        studentIdButton.setText("Search By Student Id");
        studentIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coachIdButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ratingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sportIdButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentIdButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(coachIdButton)
                .addGap(18, 18, 18)
                .addComponent(ratingButton)
                .addGap(18, 18, 18)
                .addComponent(sportIdButton)
                .addGap(18, 18, 18)
                .addComponent(studentIdButton)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coachIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachIdButtonActionPerformed
        SearchByCoachIdPage searchByCoachIdPage = new SearchByCoachIdPage();
        searchByCoachIdPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_coachIdButtonActionPerformed

    private void sportIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportIdButtonActionPerformed
        SearchBySportIdPage searchBySportIdPage = new SearchBySportIdPage();
        searchBySportIdPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sportIdButtonActionPerformed

    private void studentIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdButtonActionPerformed
        SearchByStudentIdPage searchByStudentIdPage = new SearchByStudentIdPage();
        searchByStudentIdPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentIdButtonActionPerformed

    private void ratingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingButtonActionPerformed
        try {
            File reference = new File("student.txt");
            File ratings = new File("ratings.txt");
            Scanner sc = new Scanner(reference);
            FileWriter fw = new FileWriter(ratings);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            boolean printed = false;
            int count = 0;

            while (sc.hasNext()) {
                String line = sc.nextLine();
                String[] array = line.split("\n");
                count++;

                for (int i = 0; i < array.length; i++) {
                    String[] data = array[i].split(",");
                    
                    if(data.length!=count && !printed){
                        pw.print(data.length);
                        pw.print("\n");
                        printed = true;
                    }
                    pw.print(data[4]);
                    pw.print("\n");
                    pw.print(data[5]);
                    pw.print("\n");
                }
            }

            sc.close();
            pw.flush();
            pw.close();

            SearchByCoachRatingPage searchByCoachRatingPage = new SearchByCoachRatingPage();
            searchByCoachRatingPage.setVisible(true);
            this.dispose();

        } catch (IOException e) {

        }
    }//GEN-LAST:event_ratingButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdminMainPage adminMainPage = new AdminMainPage();
        adminMainPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDisplayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDisplayPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coachIdButton;
    private javax.swing.JButton jButton2;
    protected javax.swing.JButton ratingButton;
    private javax.swing.JButton sportIdButton;
    private javax.swing.JButton studentIdButton;
    // End of variables declaration//GEN-END:variables
}
