/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.assignment;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author rong0
 */
public class StudentMainPage extends javax.swing.JFrame {

    /**
     * Creates new form StudentMainPage
     */
    public StudentMainPage() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coachDisplayButton = new javax.swing.JButton();
        sportScheduleButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ratingButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        coachDisplayButton.setText("Coach");
        coachDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachDisplayButtonActionPerformed(evt);
            }
        });

        sportScheduleButton.setText("Sport Schedule");
        sportScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportScheduleButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");
        jLabel1.setEnabled(false);

        ratingButton.setText("Rating");
        ratingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingButtonActionPerformed(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sportScheduleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(coachDisplayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ratingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(coachDisplayButton)
                .addGap(29, 29, 29)
                .addComponent(sportScheduleButton)
                .addGap(28, 28, 28)
                .addComponent(ratingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(editButton)
                .addGap(28, 28, 28)
                .addComponent(jButton4)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coachDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachDisplayButtonActionPerformed
        StudentCoachDisplayPage coachDisplayPage = new StudentCoachDisplayPage();
        coachDisplayPage.setVisible(true);
        this.dispose();
        coachDisplayPage.jLabel2.setText(jLabel1.getText());
    }//GEN-LAST:event_coachDisplayButtonActionPerformed

    private void sportScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportScheduleButtonActionPerformed
        RegScheduleDisplayPage regScheduleDisplayPage = new RegScheduleDisplayPage();
        regScheduleDisplayPage.setVisible(true);
        regScheduleDisplayPage.jLabel2.setText(jLabel1.getText());
        this.dispose();
    }//GEN-LAST:event_sportScheduleButtonActionPerformed

    private void ratingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingButtonActionPerformed
        FeedbackPage feedbackPage = new FeedbackPage();
        feedbackPage.setVisible(true);
        feedbackPage.nameField.setText(jLabel1.getText());
        this.dispose();
    }//GEN-LAST:event_ratingButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        String name = jLabel1.getText();
        int id = 1;

        try {
            File file = new File("student.txt");
            Scanner sc = new Scanner(file);

            while (sc.hasNext()) {
                String s = sc.next();
                String[] array = s.split("\n");

                for (int i = 0; i < array.length; i++) {
                    {
                        String[] sArray = array[i].split(",");

                        String password = sArray[2];
                        String sports = sArray[3];
                        String coach = sArray[4];
                        String rating = sArray[5];

                        if (name.equals(sArray[1])) {
                            StudentEditPage studentEditPage = new StudentEditPage();
                            studentEditPage.setVisible(true);
                            this.dispose();
                            studentEditPage.nameField.setText(jLabel1.getText());
                            studentEditPage.passField.setText(password);
                            studentEditPage.SportsList.setSelectedItem(sArray[3]);
                            studentEditPage.coachList.setSelectedItem(sArray[4]);
                            studentEditPage.jLabel6.setText(sArray[5]);
                            studentEditPage.jLabel7.setText(sArray[0]);
                        }
                    }
                }

            }
            sc.close();
        } catch (IOException e) {

        }


    }//GEN-LAST:event_editButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coachDisplayButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton jButton4;
    protected javax.swing.JLabel jLabel1;
    private javax.swing.JButton ratingButton;
    private javax.swing.JButton sportScheduleButton;
    // End of variables declaration//GEN-END:variables
}
